### ISSUE TITLE
Collect and Lookup formula not working together

### ISSUE THREAD

**Issue by anderson-joyle** [microsoft/Power-Fx#1057]
Cards bug #16901789

Collect(crba2_myworkmeetingpollvote, {'Meeting Name': "Test Meeting", 'Option': 1, 'Meeting Poll': LookUp(crba2_myworkmeetingpoll, 'MyWork Meeting Poll' = GUID(MeetingPollId))   });

Custom table called crba2_myworkmeetingpollvote with the columns seen above as well as a table called crba2_myworkmeetingpoll. Trying to patch a record into the vote table that has a lookup reference to the meeting poll table. 

```
Microsoft.PowerFx.Dataverse.DataverseDataSourceInfo.Microsoft.PowerFx.Core.Functions.Delegation.IDataEntityMetadata.get_EntityName()
   at Microsoft.PowerFx.Core.Types.DType.IsMatchingExpandType(DType expectedColumnType, DType actualColumnType)
   at Microsoft.PowerFx.Core.Types.DType.UnionCore(Boolean& fError, DType type1, DType type2, Boolean useLegacyDateTimeAccepts)
   at Microsoft.PowerFx.Core.Types.DType.Union(Boolean& fError, DType type1, DType type2, Boolean useLegacyDateTimeAccepts)
   at Microsoft.PowerFx.Interpreter.CollectFunction.CheckTypes(TexlNode[] args, DType[] argTypes, IErrorContainer errors, DType& returnType, Dictionary`2& nodeToCoercedTypeMap)
   at Microsoft.PowerFx.Core.Functions.TexlFunction.HandleCheckInvocation(TexlBinding binding, TexlNode[] args, DType[] argTypes, IErrorContainer errors, DType& returnType, Dictionary`2& nodeToCoercedTypeMap)
   at Microsoft.PowerFx.Core.Binding.BinderUtils.TryGetBestOverload(TexlBinding txb, CallNode node, DType[] argTypes, TexlFunction[] overloads, TexlFunction& bestOverload, Dictionary`2& nodeToCoercedTypeMap, DType& returnType, LimitedSeverityErrorContainer& warnings)
   at Microsoft.PowerFx.Core.Binding.TexlBinding.Visitor.PreVisitWithOverloadResolution(CallNode node, TexlFunction[] overloads)
   at Microsoft.PowerFx.Core.Binding.TexlBinding.Visitor.PreVisitBottomUp(CallNode node, Int32 argCountVisited, Scope scopeNew)
   at Microsoft.PowerFx.Core.Binding.TexlBinding.Visitor.PreVisit(CallNode node)
   at Microsoft.PowerFx.Syntax.CallNode.Accept(TexlVisitor visitor)
   at Microsoft.PowerFx.Core.Binding.TexlBinding.Visitor.PreVisit(VariadicOpNode node)
   at Microsoft.PowerFx.Syntax.VariadicOpNode.Accept(TexlVisitor visitor)
   at Microsoft.PowerFx.Core.Binding.TexlBinding.Run(IBinderGlue glue, IExternalRuleScopeResolver scopeResolver, DataSourceToQueryOptionsMap queryOptionsMap, TexlNode node, INameResolver resolver, BindingConfig bindingConfig, Boolean updateDisplayNames, DType ruleScope, Boolean forceUpdateDisplayNames, IExternalRule rule, Features features)
   at Microsoft.PowerFx.Engine.CheckInternal(ParseResult parse, BindingConfig bindingConfig, ReadOnlySymbolTable symbolTable)
   at Microsoft.PowerCards.Scripting.PowerFxExpressionEvaluator.<EvalExpressionAsync>d__12.MoveNext() in C:\__w\1\s\src\PowerCards\Microsoft.PowerCards.Scripting\PowerFxExpressionEvaluator.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerCards.Scripting.PowerFxExpressionEvaluator.<EvalAsync>d__11.MoveNext() in C:\__w\1\s\src\PowerCards\Microsoft.PowerCards.Scripting\PowerFxExpressionEvaluator.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerCards.Scripting.PowerFxRecalcEngine.<EvalAsync>d__3.MoveNext() in C:\__w\1\s\src\PowerCards\Microsoft.PowerCards.Scripting\PowerFxRecalcEngine.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerCards.Scripting.PowerFxScriptRunner.<RunScriptAsync>d__12.MoveNext() in C:\__w\1\s\src\PowerCards\Microsoft.PowerCards.Scripting\PowerFxScriptRunner.cs:line 99
```

**Comment by MikeStall** [comment]
Fixed - pickup latest Dataverse.Eval nuget
