### ISSUE TITLE
`Concatenate` issues

### ISSUE THREAD

**Issue by TonyTroeff** [microsoft/Power-Fx#111]
I have the following expression:
```
Concatenate("Hello", " World!")
```

However, as simple as it looks I do not get the expected result. This is the exception I am encountering:
```
System.InvalidOperationException: Errors: Error 19-20: Unexpected characters. The formula contains 'ParenClose' where 'Error' is expected.
Error 19-20: Unexpected characters. Characters are used in the formula in an unexpected way.
   at Microsoft.PowerFx.Core.Public.CheckResult.ThrowOnErrors()
   at Microsoft.PowerFx.RecalcEngine.Eval(String expressionText, RecordValue parameters)
   ...
```

And my code is nothing special:
```
var defaultCulture = CultureInfo.CreateSpecificCulture("en");
var engine = new RecalcEngine(defaultCulture);
var result = engine.Eval(formula, contextRecord);
```

I would appreciate your help!

**Comment by TonyTroeff** [comment]
I can give some additional information that I noticed now - it actually works sometimes. But more often I receive an exception.

**Comment by TonyTroeff** [comment]
I can give even more information. This issue is happening only when the `CultureInfo.CurrentCulture` is `bg-BG` for example.

**Comment by TonyTroeff** [comment]
There is a simple test I wrote:
```
[Fact]
public async Task ConcatenationFormulaShouldBeEvaluatedCorrectlyRegardlessOfTheCulture()
{
    CultureInfo.CurrentCulture = CultureInfo.CreateSpecificCulture("bg-BG");
    CultureInfo.CurrentUICulture = CultureInfo.CreateSpecificCulture("bg-BG");

    for (var i = 0; i < 10; i++)
    {
        const string formula = "Concatenate(\"Hello\", \" World!\")";
        var defaultCulture = CultureInfo.CreateSpecificCulture("en");
        var engine = new RecalcEngine(defaultCulture);
        var result = engine.Eval(formula);

        var helloWorld = Assert.IsType<string>(result);
        Assert.Equal("Hello World!", helloWorld);
    }
}
```

**Comment by BetimBeja** [comment]
the separator for the `bg-BG` culture is `;` so the problem is that the engine is not using the `defaultCulture` of the `RecalcEngine`
The following test is a false positive

```csharp
using Microsoft.PowerFx;
using System.Globalization;
using Xunit;

public class TestPowerFx
{
    [Fact]
    public void ConcatenationFormulaShouldBeEvaluatedCorrectlyRegardlessOfTheCulture()
    {
        CultureInfo.CurrentCulture = CultureInfo.CreateSpecificCulture("bg-BG");
        CultureInfo.CurrentUICulture = CultureInfo.CreateSpecificCulture("bg-BG");

        const string formula = "Concatenate(\"Hello\"; \" World!\")";
        var defaultCulture = CultureInfo.CreateSpecificCulture("en");
        var engine = new RecalcEngine(defaultCulture);
        var result = engine.Eval(formula);

        var helloWorld = Assert.IsType<string>(result.ToObject());
        Assert.Equal("Hello World!", helloWorld);
    }
}

```

**Comment by BetimBeja** [comment]
I tried with the version af355932f128bce0443131f12b3eda482cb49638 and there are some more problems:
this is the test:
```csharp
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

using System.Globalization;
using Microsoft.PowerFx.Core;
using Xunit;

namespace Microsoft.PowerFx.Tests
{
    public class RecalcEngineTests
    {
        [Fact]
        public void ConcatenationFormulaShouldBeEvaluatedCorrectlyRegardlessOfTheCulture()
        {
            CultureInfo.CurrentCulture = CultureInfo.CreateSpecificCulture("bg-BG");
            CultureInfo.CurrentUICulture = CultureInfo.CreateSpecificCulture("bg-BG");

            const string formula = "Concatenate(\"Hello\", \" World!\")";
            var defaultCulture = CultureInfo.CreateSpecificCulture("en");
            var engine = new RecalcEngine(new PowerFxConfig(defaultCulture));
            var result = engine.Eval(formula);

            var helloWorld = Assert.IsType<string>(result.ToObject());
            Assert.Equal("Hello World!", helloWorld);
        }
    }
}
```

`CultureInfo` of `PowerFxConfig` is not being used... after making some changes to the code, it still fails to load `EnumStore` because the `LanguageConstants` class tries to load a string resource with the wrong culture `bg-BG` and the `LocaleSpecificEnum_SortOrder` string is missing from that culture.
https://github.com/microsoft/Power-Fx/blob/af355932f128bce0443131f12b3eda482cb49638/src/libraries/Microsoft.PowerFx.Core/Utils/LanguageConstants.cs#L13

**Comment by TonyTroeff** [comment]
Hello. Is there any development related to this issue?

**Comment by MikeStall** [comment]
@anderson-joyle  - can you take a loook? This may be related to the other culture issues you're looking at. 
Possibly #713

**Comment by anderson-joyle** [comment]
Hi @TonyTroeff @BetimBeja. There were some major changes lately on how the engine sets the CultureInfo value along the internal calls. The test case you provided has been added to the test cases list and it passes. Could you please get latest code and give another try? Please let me know the results.

**Comment by TonyTroeff** [comment]
I can validate from version `0.2.3-preview` that this is fixed.
