### ISSUE TITLE
Crash: Color.Red throws InvalidCastException in IR

### ISSUE THREAD

**Issue by MikeStall** [microsoft/Power-Fx#1138]
`Color.Red` expression causes crash:

System.InvalidCastException: Unable to cast object of type 'System.Double' to type 'System.UInt32'.
   at Microsoft.PowerFx.Core.IR.IRTranslator.IRTranslatorVisitor.Visit(DottedNameNode node, IRTranslatorContext context)
   at Microsoft.PowerFx.Syntax.DottedNameNode.Accept[TResult,TContext](TexlFunctionalVisitor`2 visitor, TContext context)
   at Microsoft.PowerFx.Core.IR.IRTranslator.Translate(TexlBinding binding)
   at Microsoft.PowerFx.CheckResult.ApplyIR()
   at Microsoft.PowerFx.CheckResultExtensions.GetEvaluator(CheckResult result, StackDepthCounter stackMarker)
   at FxPlayground.Core.Session.TryEvalAsync(String expression, UserInfo user, CancellationToken cancel) in D:\dev\pa2\PowerFxPlayground\src\FxPlaygroundCore\Session.cs:line 391
   at PowerFxService.Controllers.EvaluationController.HandleRequestAsync(String session, RequestBody body) in D:\dev\pa2\PowerFxPlayground\src\WebDemo\Controllers\EvaluationController.cs:line 194

http://aka.ms/fxplayground?session=mike1#expr_Q29sb3IuUmVk

**Comment by MikeStall** [comment]
Found this while looking at #723, may be related.

**Comment by nguhoa** [comment]
Fixed in https://github.com/microsoft/Power-Fx/pull/1152
