### ISSUE TITLE
crash with decimal - coercion to 32-bit int internal to interpreter

### ISSUE THREAD

**Issue by MikeStall** [microsoft/Power-Fx#1288]
Mid("asdf",1e28,2)
Mid("hello", Float(1e28), 2)

Hits exception: 

System.ArgumentOutOfRangeException: StartIndex cannot be less than zero. (Parameter 'startIndex')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Microsoft.PowerFx.Functions.Library.Mid(IRContext irContext, FormulaValue[] args)
   at Microsoft.PowerFx.Functions.Library.<>c__DisplayClass403_0`1.<StandardErrorHandling>b__0(EvalVisitor runner, EvalVisitorContext context, IRContext irContext, T[] args)
   at Microsoft.PowerFx.Functions.Library.<>c__DisplayClass402_0`1.<<StandardErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.PowerFx.EvalVisitor.Visit(CallNode node, EvalVisitorContext context)
   at Microsoft.PowerFx.ParsedExpression.EvalAsync(CancellationToken cancellationToken, IRuntimeConfig runtimeConfig)
   at FxPlayground.Core.Session.TryEvalAsync(String expression, UserInfo user, CancellationToken cancel) in D:\dev\pa2\PowerFxPlayground\src\FxPlaygroundCore\Session.cs:line 514

**Comment by gregli-msft** [comment]
I believe this is the internal coercion to Int problem, a pre-exisitng condition before Decimal.

**Comment by gregli-msft** [comment]
It fails very close to the 32-bit signed int boundary:
```
> Mid("asfd",2147483647,1)
""

> Mid("asfd",2147483648,1)
""

> Mid("asfd",2147483649,1)
One or more errors occurred. (StartIndex cannot be less than zero. (Parameter 'startIndex'))
```

**Comment by gregli-msft** [comment]
In fixing this, it is likely not isoalted to Mid.  We should check all int coercions in the interpreter, and the compiler for that matter.
