### ISSUE TITLE
Crash: First(Accounts).Tasks causes exception 

### ISSUE THREAD

**Issue by MikeStall** [microsoft/Power-Fx#1336]
`First(Accounts).Tasks`

System.NotSupportedException: Specified method is not supported.
   at Microsoft.PowerFx.Core.IR.IRTranslator.IRTranslatorVisitor.Visit(DottedNameNode node, IRTranslatorContext context)
   at Microsoft.PowerFx.Syntax.DottedNameNode.Accept[TResult,TContext](TexlFunctionalVisitor`2 visitor, TContext context)
   at Microsoft.PowerFx.Core.IR.IRTranslator.Translate(TexlBinding binding)
   at Microsoft.PowerFx.CheckResult.ApplyIR()
   at Microsoft.PowerFx.CheckResultExtensions.GetEvaluator(CheckResult result, StackDepthCounter stackMarker)
   at FxPlayground.Core.Session.TryEvalAsync(String expression, UserInfo user, CancellationToken cancel) in D:\dev\pa2\PowerFxPlayground\src\FxPlaygroundCore\Session.cs:line 519

Like from here, because Account.Tasks is a relationship and that's not supported. 
https://github.com/microsoft/Power-Fx/blob/bbeb145263301f5caa8f21ece945401e456605f8/src/libraries/Microsoft.PowerFx.Core/IR/IRTranslator.cs#L609

Likely because Accounts.Tasks is a 1:N relationship

**Comment by lesaltzm** [comment]
Could pretty easily just remove that check and treat it like a field access. The backing RecordValue can handle that it's a relationship, the IR doesn't need to.
