### ISSUE TITLE
fError with AsType crashes

### ISSUE THREAD

**Issue by MikeStall** [microsoft/Power-Fx#1365]
`IfError((AsType(First(Accounts).Owner,Queues)),AsType(First(Accounts).Owner,Users))`

Crashes:

Microsoft.PowerFx.Interpreter.CustomFunctionErrorException: Runtime type mismatch
   at Microsoft.PowerFx.EvalVisitor.Visit(CallNode node, EvalVisitorContext context)
   at Microsoft.PowerFx.ParsedExpression.EvalAsync(CancellationToken cancellationToken, IRuntimeConfig runtimeConfig)
   at FxPlayground.Core.Session.TryEvalAsync(String expression, UserInfo user, CancellationToken cancel) in D:\dev\pa2\PowerFxPlayground\src\FxPlaygroundCore\Session.cs:line 477
   at PowerFxService.Controllers.EvaluationController.HandleRequestAsync(String session, RequestBody body) in D:\dev\pa2\PowerFxPlayground\src\WebDemo\Controllers\EvaluationController.cs:line 159

**Comment by MikeStall** [comment]
#1173 would probably fix this; but that's a breaking change. 
#1350 added AsType

**Comment by MikeStall** [comment]
There may be 2 issues there:
- runtime mismatch
- exception is not getting caught and is leaking out past EvalAsync

Another issue with same stack:
This works:
`First(Accounts).Owner`
But this fails: 
`With( { record : First(Accounts)}, record.Owner) `
