### ISSUE TITLE
Crash when CurrentUICulture is Invariant

### ISSUE THREAD

**Issue by jcoc611-microsoft** [microsoft/Power-Fx#1553]
We would like to run with `CultureInfo.CurrentUICulture = CultureInfo.InvariantCulture`. However this causes a crash because BaseError's constructor does not use the culture we set on `PowerFxConfig`. I think you should either fall back to `en` in this case, or use the culture set on RecalcEngine with PowerFxConfig.

```
System.ArgumentException: locale
   at Microsoft.PowerFx.Core.Utils.Contracts.CheckNonEmpty(String s, String paramName)
   at Microsoft.PowerFx.Core.Localization.StringResources.TryGetErrorResource(ErrorResourceKey resourceKey, ErrorResource& resourceValue, String locale)
   at Microsoft.PowerFx.Core.Errors.ErrorUtils.GetLocalizedErrorContent(ErrorResourceKey errKey, CultureInfo locale, ErrorResource& errorResource)
   at Microsoft.PowerFx.Core.Errors.BaseError..ctor(IDocumentError innerError, Exception internalException, DocumentErrorKind kind, DocumentErrorSeverity severity, ErrorResourceKey errKey, Span textSpan, IEnumerable`1 sinkTypeErrors, Object[] args)
   at Microsoft.PowerFx.Core.Errors.BaseError..ctor(IDocumentError innerError, Exception internalException, DocumentErrorKind kind, DocumentErrorSeverity severity, ErrorResourceKey errKey, Object[] args)
   at Microsoft.PowerFx.Core.Errors.TexlError..ctor(TexlNode node, DocumentErrorSeverity severity, ErrorResourceKey errKey, Object[] args)
   at Microsoft.PowerFx.Core.App.ErrorContainers.ErrorContainer.Error(DocumentErrorSeverity severity, TexlNode node, ErrorResourceKey errKey, Object[] args)
   at Microsoft.PowerFx.Core.App.ErrorContainers.ErrorContainer.Error(TexlNode node, ErrorResourceKey errKey, Object[] args)
   at Microsoft.PowerFx.Core.Binding.TexlBinding.Visitor.Visit(FirstNameNode node)
   at Microsoft.PowerFx.Syntax.FirstNameNode.Accept(TexlVisitor visitor)
   at Microsoft.PowerFx.Core.Binding.TexlBinding.Visitor.Run()
   at Microsoft.PowerFx.Core.Binding.TexlBinding.Run(IBinderGlue glue, IExternalRuleScopeResolver scopeResolver, DataSourceToQueryOptionsMap queryOptionsMap, TexlNode node, INameResolver resolver, BindingConfig bindingConfig, Boolean updateDisplayNames, DType ruleScope, Boolean forceUpdateDisplayNames, IExternalRule rule, Features features)
   at Microsoft.PowerFx.Core.Binding.TexlBinding.Run(IBinderGlue glue, TexlNode node, INameResolver resolver, BindingConfig bindingConfig, DType ruleScope, Features features)
   at Microsoft.PowerFx.Engine.CheckInternal(ParseResult parse, BindingConfig bindingConfig, ReadOnlySymbolTable symbolTable)
   at Microsoft.PowerFx.Engine.Check(ParseResult parse, ParserOptions options, ReadOnlySymbolTable symbolTable)
   at Microsoft.PowerFx.Engine.Check(String expressionText, ParserOptions options, ReadOnlySymbolTable symbolTable)
   ...

**Comment by MikeStall** [comment]
For error messages, we actually can get them lazily.  So a single error could even be retrieved for multiple cultures.  See CheckResult.GetErrorsInLocale(): 

https://github.com/microsoft/Power-Fx/blob/02ae0997e791727a854aa3ea07adc6e09677248f/src/libraries/Microsoft.PowerFx.Core/Public/CheckResult.cs#L312

@jcoc611-microsoft  - can you confirm that would unblock your scenario? 

@nguhoa  - That aside, we still shouldn't crash here. Setting to invariant, should just fallback to en-us.  We don't have access to the config at this layer in the stack.

**Comment by nguhoa** [comment]
Fixed in https://github.com/microsoft/Power-Fx/pull/1559
