### ISSUE TITLE
`Text(5/2)` causes crash in french locale

### ISSUE THREAD

**Issue by MikeStall** [microsoft/Power-Fx#1757]
`Text(5/2)`

running In french locale,  
// Culture: parse= fr-FR, runtime= fr-FR, 

System.InvalidOperationException: Instance is read-only.
   at System.Globalization.NumberFormatInfo.VerifyWritable()
   at System.Globalization.NumberFormatInfo.set_NumberGroupSeparator(String value)
   at Microsoft.PowerFx.Functions.Library.TryText(FormattingInfo formatInfo, IRContext irContext, FormulaValue value, TextFormatArgs textFormatArgs, StringValue& result, CancellationToken cancellationToken)
   at Microsoft.PowerFx.Functions.Library.Text(FormattingInfo formatInfo, IRContext irContext, FormulaValue[] args, CancellationToken cancellationToken)
   at Microsoft.PowerFx.Functions.Library.Text(EvalVisitor runner, EvalVisitorContext context, IRContext irContext, FormulaValue[] args)
   at Microsoft.PowerFx.Functions.Library.<>c__DisplayClass465_0`1.<StandardErrorHandling>b__0(EvalVisitor runner, EvalVisitorContext context, IRContext irContext, T[] args)
   at Microsoft.PowerFx.Functions.Library.<>c__DisplayClass462_0`1.<<StandardErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.PowerFx.EvalVisitor.Visit(CallNode node, EvalVisitorContext context)
   at Microsoft.PowerFx.ParsedExpression.EvalAsync(CancellationToken cancellationToken, IRuntimeConfig runtimeConfig)

http://aka.ms/fxplayground?session=french#expr_VGV4dCgxMjMsNDU2KQ==

**Comment by MikeStall** [comment]
Problem is here:
https://github.com/microsoft/Power-Fx/blob/d89177f6a887619c39eb5771c81a9a5bb9b57ed4/src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryText.cs#L401

We can't assume culture is mutable.  Regressed with #1577.

**Comment by MikeStall** [comment]
Here's a test case that repros the crash:

        [Fact]
        public void RecalcEngine_FrenchDecimal()
        {
            var culture = new CultureInfo("fr-FR");
            culture.NumberFormat.NumberGroupSeparator = "\u00A0";
            culture.NumberFormat = NumberFormatInfo.ReadOnly(culture.NumberFormat);

            Assert.True(culture.NumberFormat.IsReadOnly);

            var engine = new RecalcEngine(new PowerFxConfig());

            var expr = "Text(5/2)";
            //expr = "Language()";
            
            var rc = new RuntimeConfig();
            rc.SetCulture(culture);

            var result = engine.EvalAsync(expr, default, runtimeConfig: rc).Result;            
        }
