### ISSUE TITLE
Setting a decimal variable with float throws

### ISSUE THREAD

**Issue by anderson-joyle** [microsoft/Power-Fx#1861]
Try `Set(x, 1)`
Then `Set(x, Float(1))`

```
System.InvalidOperationException: Can't change ''x:Globals_22150220'' from Decimal to n.
   at Microsoft.PowerFx.ReadOnlySymbolTable.ValidateAccepts(ISymbolSlot slot, FormulaType newType)
   at Microsoft.PowerFx.SymbolValues.Set(ISymbolSlot slot, FormulaValue value)
   at Microsoft.PowerFx.RecalcEngine.UpdateVariable(String name, FormulaValue value)
   at FxPlayground.Core.Session.AddVariable(String name, FormulaValue value) in D:\dev\pa2\PowerFxPlayground\src\FxPlaygroundCore\Session.cs:line 917
   at PowerFxService.Controllers.EvaluationController.HandleRequestAsync(String session, RequestBody body) in D:\dev\pa2\PowerFxPlayground\src\WebDemo\Controllers\EvaluationController.cs:line 141
```

http://aka.ms/fxplayground?session=joyle7#expr_U2V0KHgsIEZsb2F0KDEpKQ==

**Comment by MikeStall** [comment]
Is the issue here that Set() should coerce it's arg?  Ie, in this case, x was declared as decimal, so the Float(1) should get coerced to decimal?

**Comment by jas-valgotar** [comment]
This looks like something specific to the playground site's Set() hack, Repl works fine and does coerce the Arg.
![image](https://github.com/microsoft/Power-Fx/assets/32079188/92db7715-2a6b-49ea-a9e9-8ce685a2fdf4)
