### ISSUE TITLE
Crash when using AsType

### ISSUE THREAD

**Issue by MikeStall** [microsoft/Power-Fx#1961]
`CountRows(Notes)` is 0.  // important to get the blank 

`AsType(First(Notes).Regarding, Cases).Case`

System.InvalidCastException: Unable to cast object of type 'Microsoft.PowerFx.Types.BlankValue' to type 'Microsoft.PowerFx.Types.RecordValue'.
   at Microsoft.PowerFx.Functions.Library.AsType(EvalVisitor runner, EvalVisitorContext context, IRContext irContext, FormulaValue[] args)
   at Microsoft.PowerFx.Functions.Library.<>c__DisplayClass465_0`1.<<StandardErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.PowerFx.EvalVisitor.Visit(CallNode node, EvalVisitorContext context)
   at Microsoft.PowerFx.EvalVisitor.Visit(RecordFieldAccessNode node, EvalVisitorContext context)
   at Microsoft.PowerFx.ParsedExpression.EvalAsync(CancellationToken cancellationToken, IRuntimeConfig runtimeConfig)
   at FxPlayground.Core.Session.TryEvalAsync(String expression, UserInfo user, CancellationToken cancel) in D:\dev\pa2\PowerFxPlayground\src\FxPlaygroundCore\Session.cs:line 634
   at PowerFxService.Controllers.EvaluationController.HandleRequestAsync(String session, RequestBody body) in D:\dev\pa2\PowerFxPlayground\src\WebDemo\Controllers\EvaluationController.cs:line 221

**Comment by MikeStall** [comment]
AsType arg 0 is blank. 
https://github.com/microsoft/Power-Fx/blob/9c0b9c4254baffa63bffc2dca8f3a8cdaf7c0cce/src/libraries/Microsoft.PowerFx.Interpreter/Functions/LibraryTable.cs#L577

We should either just have a check for blank, or the pipeline in Library.cs should have handled for us.

**Comment by jas-valgotar** [comment]
Fixed via https://github.com/microsoft/Power-Fx/pull/1969
