### ISSUE TITLE
Connector: office365Outlook, operation: FindMeetingTimesV2 not working

### ISSUE THREAD

**Issue by coletaylor1** [microsoft/Power-Fx#2045]
The [find meeting times v2](https://learn.microsoft.com/en-us/connectors/office365/#find-meeting-times-(v2)) action of the Office 365 Outlook connector is not working. Intellisense suggests out all the parameters listed in the documentation but after completing the function, it complains about the number of arguments. It fails on evaluation with the same error.

![image](https://github.com/microsoft/Power-Fx/assets/72627659/e18a323f-9aca-4b0f-bbb6-c84da8b36f50)

![image](https://github.com/microsoft/Power-Fx/assets/72627659/b1317192-eceb-421d-914a-7d51b1ff3ec6)

![image](https://github.com/microsoft/Power-Fx/assets/72627659/6ac5fd10-e71a-40d2-98b2-9661bf371e7c)

```
office365Outlook.FindMeetingTimesV2("tenantadmin@powerappscardsdev.onmicrosoft.com", "", "", 30, Now(), DateAdd(Now(), 7, TimeUnit.Days), 3, "100", false, "Work") - Error 0-162: Invalid number of arguments: received 10, expected 0-1.
```

**Comment by coletaylor1** [comment]
From some other testing of the same connector:

V4CalendarGetItems - works
V4CalendarPostItem - fails (unexpected error)

**Comment by coletaylor1** [comment]
Stack trace for post item failure:

`office365Outlook.V4CalendarPostItem("Calendar", "Test Event", DateTime(2023, 11, 13, 11, 00, 00), DateTime(2023, 11, 13, 11, 30, 00), "PST")`

```
System.ArgumentException: Expected StringValue and got ErrorValue value, for property start
   at Microsoft.PowerFx.Connectors.Execution.FormulaValueSerializer.WriteProperty(String propertyName, OpenApiSchema propertySchema, FormulaValue fv)
   at Microsoft.PowerFx.Connectors.HttpFunctionInvoker.GetBody(String referenceId, Boolean schemaLessBody, Dictionary`2 map, IConvertToUTC utcConverter, CancellationToken cancellationToken)
   at Microsoft.PowerFx.Connectors.HttpFunctionInvoker.BuildRequest(FormulaValue[] args, IConvertToUTC utcConverter, CancellationToken cancellationToken)
   at Microsoft.PowerFx.Connectors.HttpFunctionInvoker.<InvokeAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerFx.Connectors.ConnectorFunction.<InvokeInternalAsync>d__93.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerFx.Connectors.ConnectorTexlFunction.<InvokeAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerFx.EvalVisitor.<Visit>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerFx.ParsedExpression.<EvalAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerCards.Scripting.PowerFxExpressionEvaluator.<EvalExpressionAsync>d__13.MoveNext() in C:\__w\1\s\src\PowerCards\Microsoft.PowerCards.Scripting\PowerFxExpressionEvaluator.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerCards.Scripting.PowerFxExpressionEvaluator.<EvalAsync>d__12.MoveNext() in C:\__w\1\s\src\PowerCards\Microsoft.PowerCards.Scripting\PowerFxExpressionEvaluator.cs:line 71
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerCards.Scripting.PowerFxRecalcEngine.<EvalAsync>d__3.MoveNext() in C:\__w\1\s\src\PowerCards\Microsoft.PowerCards.Scripting\PowerFxRecalcEngine.cs:line 50
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerCards.Scripting.PowerFxScriptRunner.<RunScriptAsync>d__15.MoveNext() in C:\__w\1\s\src\PowerCards\Microsoft.PowerCards.Scripting\PowerFxScriptRunner.cs:line 196
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerCards.TeamsActionContext.<>c__DisplayClass37_0.<<ProcessVerbsAsync>b__0>d.MoveNext() in C:\__w\1\s\src\PowerCards\Microsoft.PowerCards\TeamsActionContext.cs:line 310
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerCards.HTTP.Telemetry.TelemetryExtensions.<>c__DisplayClass1_0.<<ExecuteCallerAsync>b__0>d.MoveNext() in C:\__w\1\s\src\PowerCards\Microsoft.PowerCards.HTTP\Telemetry\TelemetryExtensions.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.<ExecuteAsync>d__11`1.MoveNext()
```

**Comment by coletaylor1** [comment]
Adding a few other actions I've tried from spot testing and failures:

office365Outlook.ContactPostItemV2("Contacts", "John Smith", ["123-456-7890"]) - Error: office365Outlook.ContactPostItemV2 failed: The server returned an HTTP error with code 400. Response: { "error": { "code": "invalidRequest", "message": "The provided encoding is not supported." } }

office365Outlook.ContactPatchItemV2("Contacts", First(office365Outlook.ContactGetItemsV2("Contacts").value).id, "Connor", ["123-456-7890"]) - Error: office365Outlook.ContactPatchItemV2 failed: The server returned an HTTP error with code 400. Response: { "error": { "code": "invalidRequest", "message": "The provided encoding is not supported." ...
