### ISSUE TITLE
System.NotImplementedException because of missing Check for JSON in HttpFunctionInvoker.cs:DecodeResponseAsync

### ISSUE THREAD

**Issue by ckkashyap** [microsoft/Power-Fx#2106]
We ran into the following exception while calling a connector. It would be better if Pfx throws a PowerFxConnectorException here.

System.NotImplementedException: Expecting a StringType but got Record
   at Microsoft.PowerFx.Types.FormulaValueJSON.FromJson(JsonElement element, FormulaType formulaType, Boolean numberIsFloat)
   at Microsoft.PowerFx.Types.FormulaValueJSON.RecordFromJsonObject(JsonElement element, RecordType recordType, Boolean numberIsFloat)
   at Microsoft.PowerFx.Types.FormulaValueJSON.FromJson(JsonElement element, FormulaType formulaType, Boolean numberIsFloat)
   at Microsoft.PowerFx.Types.FormulaValueJSON.TableFromJsonArray(JsonElement array, TableType tableType, Boolean numberIsFloat)
   at Microsoft.PowerFx.Types.FormulaValueJSON.FromJson(JsonElement element, FormulaType formulaType, Boolean numberIsFloat)
   at Microsoft.PowerFx.Types.FormulaValueJSON.FromJson(String jsonString, FormulaType formulaType, Boolean numberIsFloat)
   at Microsoft.PowerFx.Connectors.HttpFunctionInvoker.DecodeResponseAsync(HttpResponseMessage response, Boolean throwOnError)

**Comment by LucGenetier** [comment]
Beyond providing a better exception/error, I'd like to understand better what leads to this issue.
Can you provide more information on how to reproduce this issue?

**Comment by LucGenetier** [comment]
See https://msazure.visualstudio.com/CCI/_workitems/edit/26055433
