### ISSUE TITLE
System.OverflowException: Value was either too large or too small for a Decimal.

### ISSUE THREAD

**Issue by MikeStall** [microsoft/Power-Fx#2270]
System.OverflowException: Value was either too large or too small for a Decimal.
   at System.Number.ParseDecimal(String value, NumberStyles options, NumberFormatInfo numfmt)
   at Microsoft.OpenApi.Readers.V2.OpenApiV2Deserializer.<>c.<.cctor>b__83_141(OpenApiSchema o, ParseNode n)
   at Microsoft.OpenApi.Readers.ParseNodes.PropertyNode.ParseField[T](T parentInstance, IDictionary`2 fixedFields, IDictionary`2 patternFields)
   at Microsoft.OpenApi.Readers.V2.OpenApiV2Deserializer.LoadSchema(ParseNode node)
   at Microsoft.OpenApi.Readers.ParseNodes.MapNode.<>c__DisplayClass6_0`1.<CreateMap>b__0(KeyValuePair`2 n)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Microsoft.OpenApi.Readers.V2.OpenApiV2Deserializer.<>c.<.cctor>b__83_158(OpenApiSchema o, ParseNode n)
   at Microsoft.OpenApi.Readers.ParseNodes.PropertyNode.ParseField[T](T parentInstance, IDictionary`2 fixedFields, IDictionary`2 patternFields)
   at Microsoft.OpenApi.Readers.V2.OpenApiV2Deserializer.LoadSchema(ParseNode node)
   at Microsoft.OpenApi.Readers.V2.OpenApiV2VersionService.LoadElement[T](ParseNode node)
   at Microsoft.OpenApi.Readers.ParsingContext.ParseFragment[T](YamlDocument yamlDocument, OpenApiSpecVersion version)
   at Microsoft.OpenApi.Readers.OpenApiYamlDocumentReader.ReadFragment[T](YamlDocument input, OpenApiSpecVersion version, OpenApiDiagnostic& diagnostic)
   at Microsoft.OpenApi.Readers.OpenApiTextReaderReader.ReadFragment[T](TextReader input, OpenApiSpecVersion version, OpenApiDiagnostic& diagnostic)
   at Microsoft.OpenApi.Readers.OpenApiStringReader.ReadFragment[T](String input, OpenApiSpecVersion version, OpenApiDiagnostic& diagnostic)
   at Microsoft.PowerFx.Connectors.ConnectorFunction.<GetConnectorSuggestionsFromDynamicSchemaAsync>d__98.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerFx.Connectors.ConnectorFunction.<GetConnectorSuggestionsInternalAsync>d__85.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerFx.Connectors.ConnectorTexlFunction.<GetConnectorSuggestionsAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerFx.Intellisense.IntellisenseHelper.AddTopLevelSuggestionsForCursorType(IntellisenseData intellisenseData, CallNode callNode, Int32 argPosition)
   at Microsoft.PowerFx.Intellisense.IntellisenseHelper.AddTopLevelSuggestionsForGivenNode(IntellisenseData intellisenseData, TexlNode node, TexlNode currentNode)
   at Microsoft.PowerFx.Intellisense.Intellisense.ErrorNodeSuggestionHandlerBase.TryAddSuggestionsForNodeKind(IntellisenseData intellisenseData)
   at Microsoft.PowerFx.Intellisense.Intellisense.Suggest(IntellisenseContext context, TexlBinding binding, Formula formula)
   at Microsoft.PowerFx.Engine.Suggest(CheckResult checkResult, Int32 cursorPosition, IServiceProvider services)
   at Microsoft.PowerFx.LanguageServerProtocol.LanguageServer.HandleCompletionRequest(String id, String paramsJson)
   at Microsoft.PowerFx.LanguageServerProtocol.LanguageServer.OnDataReceived(String jsonRpcPayload)

**Comment by MikeStall** [comment]
2 things to consider:
1. Why did we get the exception? Bad swagger, etc?
2. Even if there is bad swagger ... what is the customer experience?  Ideally, we don't crash. And other unrelated intellisense queries should still work. And the exception would be ignored (and logged) if it's not impacting to the customer
