### ISSUE TITLE
Intellisense failure: An item with the same key has already been added.

### ISSUE THREAD

**Issue by jas-valgotar** [microsoft/Power-Fx#2325]
This was a stack trace we recieved from Plugins folks.
(Related Plugins vso item: https://dynamicscrm.visualstudio.com/OneCRM/_workitems/edit/3947865/)

An item with the same key has already been added.

System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.PowerFx.Core.ExpressionLocalizationHelper.ConvertExpression(String expressionText, RecordType parameters, BindingConfig bindingConfig, INameResolver resolver, IBinderGlue binderGlue, ParserOptions options, Features flags, Boolean toDisplay)
   at Microsoft.PowerFx.Engine.GetDisplayExpression(String expressionText, ReadOnlySymbolTable symbolTable, CultureInfo culture)
   at Microsoft.PowerFx.LanguageServerProtocol.LanguageServer.HandleInitialFixupRequest(String id, String paramsJson)
   at Microsoft.PowerFx.LanguageServerProtocol.LanguageServer.OnDataReceived(String jsonRpcPayload)

**Comment by LucGenetier** [comment]
This callstack is prior to https://github.com/microsoft/Power-Fx/pull/2308
