### ISSUE TITLE
Crash for ForAll with two fields

### ISSUE THREAD

**Issue by gregli-msft** [microsoft/Power-Fx#647]
```
Microsoft Power Fx Console Formula REPL, Version 0.3.0.0
Enter Excel formulas.  Use "Help()" for details.

> ForAll( [1,2,3], { V: Value } )
Table({V:1}, {V:2}, {V:3})

> ForAll( [1,2,3], { C: 1 } )
Table({C:1}, {C:1}, {C:1})

> ForAll( [1,2,3], { V: Value, C: 1 } )
Server debug failure: Assertion Failed. Callstack:    at System.Environment.get_StackTrace()
   at Microsoft.PowerFx.Core.Utils.Contracts.DbgFailCore(String msg) in D:\repos\pfx-bugs\src\libraries\Microsoft.PowerFx.Core\Utils\Validation.cs:line 1353
   at Microsoft.PowerFx.Core.Utils.Contracts.DbgFail() in D:\repos\pfx-bugs\src\libraries\Microsoft.PowerFx.Core\Utils\Validation.cs:line 1394
   at Microsoft.PowerFx.Core.Utils.Contracts.Assert(Boolean f) in D:\repos\pfx-bugs\src\libraries\Microsoft.PowerFx.Core\Utils\Validation.cs:line 447
   at Microsoft.PowerFx.Types.TableType.get_SingleColumnFieldName() in D:\repos\pfx-bugs\src\libraries\Microsoft.PowerFx.Core\Public\Types\TableType.cs:line 79
   at Microsoft.PowerFx.Functions.Library.StandardTableNodeRecords(IRContext irContext, FormulaValue[] args, Boolean forceSingleColumn) in D:\repos\pfx-bugs\src\libraries\Microsoft.PowerFx.Interpreter\Functions\Library.cs:line 1431
   at Microsoft.PowerFx.Functions.Library.ForAll(EvalVisitor runner, EvalVisitorContext context, IRContext irContext, FormulaValue[] args) in D:\repos\pfx-bugs\src\libraries\Microsoft.PowerFx.Interpreter\Functions\Library.cs:line 1736
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.PowerFx.Functions.Library.ForAll(EvalVisitor runner, EvalVisitorContext context, IRContext irContext, FormulaValue[] args)
   at Microsoft.PowerFx.Functions.Library.<>c__DisplayClass257_0`1.<<StandardErrorHandlingAsync>b__0>d.MoveNext() in D:\repos\pfx-bugs\src\libraries\Microsoft.PowerFx.Interpreter\Functions\StandardErrorHandling.cs:line 115
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.PowerFx.Functions.Library.<>c__DisplayClass257_0`1.<StandardErrorHandlingAsync>b__0(EvalVisitor runner, EvalVisitorContext context, IRContext irContext, FormulaValue[] args)
   at Microsoft.PowerFx.EvalVisitor.Visit(CallNode node, EvalVisitorContext context) in D:\repos\pfx-bugs\src\libraries\Microsoft.PowerFx.Interpreter\EvalVisitor.cs:line 251
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.PowerFx.EvalVisitor.Visit(CallNode node, EvalVisitorContext context)
   at Microsoft.PowerFx.Core.IR.Nodes.CallNode.Accept[TResult,TContext](IRNodeVisitor`2 visitor, TContext context) in D:\repos\pfx-bugs\src\libraries\Microsoft.PowerFx.Core\IR\Nodes\CallNode.cs:line 74
   at Microsoft.PowerFx.ParsedExpression.EvalAsync(CancellationToken cancel, ReadOnlySymbolValues runtimeConfig) in D:\repos\pfx-bugs\src\libraries\Microsoft.PowerFx.Interpreter\ParsedExpression.cs:line 120
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.PowerFx.ParsedExpression.EvalAsync(CancellationToken cancel, ReadOnlySymbolValues runtimeConfig)
   at Microsoft.PowerFx.CheckResultExtensions.EvalAsync(IExpressionEvaluator expr, CancellationToken cancel, RecordValue parameters) in D:\repos\pfx-bugs\src\libraries\Microsoft.PowerFx.Interpreter\ParsedExpression.cs:line 45
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.PowerFx.CheckResultExtensions.EvalAsync(IExpressionEvaluator expr, CancellationToken cancel, RecordValue parameters)
   at Microsoft.PowerFx.RecalcEngine.EvalAsync(String expressionText, CancellationToken cancel, RecordValue parameters, ParserOptions options) in D:\repos\pfx-bugs\src\libraries\Microsoft.PowerFx.Interpreter\RecalcEngine.cs:line 149
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.PowerFx.RecalcEngine.EvalAsync(String expressionText, CancellationToken cancel, RecordValue parameters, ParserOptions options)
   at Microsoft.PowerFx.RecalcEngine.Eval(String expressionText, RecordValue parameters, ParserOptions options) in D:\repos\pfx-bugs\src\libraries\Microsoft.PowerFx.Interpreter\RecalcEngine.cs:line 133
   at PowerFxHostSamples.ConsoleRepl.Main() in d:\repos\pfx-bugs-samples\Samples\ConsoleREPL\ConsoleREPL.cs:line 89
```

**Comment by gregli-msft** [comment]
This is using main that I just snapped for both Power Fx and Power Fx Host Samples.
