### ISSUE TITLE
Exception in DevContainer

### ISSUE THREAD

**Issue by rajyraman** [microsoft/Power-Fx#71]
When I try to run the notebook in Dev Containers or Codespaces, I get the exception below.

```
Error: System.TypeInitializationException: The type initializer for 'Microsoft.PowerFx.Core.Texl.BuiltinFunctionsCore' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Microsoft.PowerFx.Core.Types.Enums.EnumStore' threw an exception.
 ---> System.ArgumentException: currentLocale
   at Microsoft.PowerFx.Core.Utils.Contracts.CheckNonEmpty(String s, String paramName)
   at Microsoft.PowerFx.Core.Localization.StringResources.TryGet(String resourceKey, String& resourceValue, String locale)
   at Microsoft.PowerFx.Core.Localization.StringResources.Get(String resourceKey, String locale)
   at Microsoft.PowerFx.Core.Utils.LanguageConstants.get_SortOrderEnumString()
   at Microsoft.PowerFx.Core.Types.Enums.EnumStore..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.PowerFx.Core.Types.Enums.EnumStore.get_EnumSpec()
   at Microsoft.PowerFx.Core.Types.Enums.EnumStore.TryGetEnumSpec(String name, String& dType)
   at Microsoft.PowerFx.Core.Types.Enums.EnumStore.GetEnum(String name)
   at Microsoft.PowerFx.Core.Types.ErrorType.get_ReifiedErrorSchema()
   at Microsoft.PowerFx.Core.Types.ErrorType.ReifiedError()
   at Microsoft.PowerFx.Core.Texl.Builtins.IfErrorFunction..ctor()
   at Microsoft.PowerFx.Core.Texl.BuiltinFunctionsCore..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.PowerFx.Core.Texl.BuiltinFunctionsCore.get_BuiltinFunctionsLibrary()
   at Microsoft.PowerFx.Core.Glue.SimpleResolver..ctor(TexlFunction[] extraFunctions)
   at Microsoft.PowerFx.Core.Glue.SimpleResolver..ctor(IEnumerable`1 enumSymbols, TexlFunction[] extraFunctions)
   at Microsoft.PowerFx.RecalcEngineResolver..ctor(RecalcEngine parent, RecordType parameters, IEnumerable`1 enumSymbols, TexlFunction[] extraFunctions)
   at Microsoft.PowerFx.RecalcEngine.CheckInternal(String expressionText, FormulaType parameterType, Boolean intellisense)
   at Microsoft.PowerFx.RecalcEngine.Check(String expressionText, FormulaType parameterType)
   at Microsoft.PowerFx.RecalcEngine.Eval(String expressionText, RecordValue parameters)
   at PowerFxDotnetInteractive.PowerFxExpression.EvaluateSingleExpression(String originalExpression, String expression)
   at PowerFxDotnetInteractive.PowerFxExpression.Evaluate()
   at PowerFxDotnetInteractive.PowerFxKernel.HandleAsync(SubmitCode code, KernelInvocationContext context)
   at Microsoft.DotNet.Interactive.Kernel.HandleAsync(KernelCommand command, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\Kernel.cs:line 257
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.<BuildPipeline>b__6_0(KernelCommand command, KernelInvocationContext context, KernelPipelineContinuation _) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 57
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_1.<<BuildPipeline>b__3>d.MoveNext() in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 73
--- End of stack trace from previous location ---
   at Microsoft.DotNet.Interactive.CompositeKernel.LoadExtensions(KernelCommand command, KernelInvocationContext context, KernelPipelineContinuation next) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\CompositeKernel.cs:line 144
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.<>c__DisplayClass6_0.<<BuildPipeline>g__Combine|2>d.MoveNext() in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 74
--- End of stack trace from previous location ---
   at Microsoft.DotNet.Interactive.KernelCommandPipeline.SendAsync(KernelCommand command, KernelInvocationContext context) in D:\a\_work\1\s\src\Microsoft.DotNet.Interactive\KernelCommandPipeline.cs:line 48
```

It seems to be something to do with Culture. I tried to set `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT` to false and also install `libicu-dev` (as per https://andrewlock.net/dotnet-core-docker-and-cultures-solving-culture-issues-porting-a-net-core-app-from-windows-to-linux/), but it doesn't seem to fix it.

My Dev Container config is in https://github.com/rajyraman/Power-Fx-.NET-Interactive

**Comment by Felx-B** [comment]
Hi
I had a similar issue while running powerfx in unit tests.
The only way I found to fix it, was to explicitly set the culture
```cs
CultureInfo.CurrentCulture = new CultureInfo("en-US");
```

**Comment by joebo** [comment]
I was able to work around this in a new notebook on my own jupyter installation by using this at the top of my notebook

```
using static System.Globalization.CultureInfo;
DefaultThreadCurrentCulture = GetCultureInfo("en-US");
```

**Comment by MikeStall** [comment]
sounds like issue was resolved. Please file new issue on current bits if you're still hitting problems.
